/**
 * src/services/githubSyncService.ts
 *
 * Persists user progress in a single `progress.json` file inside a public
 * `{user}/solarhub-data` repository using GitHub Contents API.
 *
 * The document stores one cursor per task type so the frontend can resume
 * from the next available item in each JSONL file independently.
 */

import type { TaskType } from './annotationService';
import { getStoredToken, getStoredUser } from './githubAuthService';

const PROGRESS_FILE_NAME = 'progress.json';
const PROGRESS_REPO_NAME = 'solarhub-data';

export interface ProgressDocument {
  schemaVersion: 2;
  points: number;
  streak: number;
  lastActiveDate: string | null;
  lastCompletedIdsByType: Record<TaskType, string | null>;
  updatedAt: string;
}

interface RepoConfig {
  owner: string;
  repo: string;
}

const TASK_TYPES: TaskType[] = [
  'sunspot',
  'magnetogram',
];

function createEmptyLastCompletedIdsByType(): Record<TaskType, string | null> {
  return TASK_TYPES.reduce((acc, taskType) => {
    acc[taskType] = null;
    return acc;
  }, {} as Record<TaskType, string | null>);
}

function getCurrentRepoConfig(): RepoConfig {
  const user = getStoredUser();
  if (!user?.login) {
    throw new Error('User not authenticated');
  }
  return { owner: user.login, repo: PROGRESS_REPO_NAME };
}

let cachedProgress: ProgressDocument | null = null;
let cachedSha: string | undefined;
let writeQueue: Promise<void> = Promise.resolve();

function defaultProgress(): ProgressDocument {
  return {
    schemaVersion: 2,
    points: 0,
    streak: 0,
    lastActiveDate: null,
    lastCompletedIdsByType: createEmptyLastCompletedIdsByType(),
    updatedAt: new Date().toISOString(),
  };
}

function encodeBase64Text(text: string): string {
  return btoa(unescape(encodeURIComponent(text)));
}

async function upsertRepoReadme(config: RepoConfig, token: string) {
  const readmePath = 'README.md';
  const content = `# SolarHub Data for ${config.owner}

This repository stores a small per-user progress file used by the SolarHub web app.

## What this repo contains

- \`progress.json\` — your personal progress document (schemaVersion: 2)

SolarHub uses this public repo only to persist a tiny JSON file that tracks which
images you've already annotated today and your points/streak. Nothing else is
written here by the app.

## progress.json schema (summary)

- \`schemaVersion\`: number — currently 2
- \`points\`: integer — total points you've earned
- \`streak\`: integer — consecutive-day contribution streak
- \`lastActiveDate\`: string|null — ISO date of last activity
- \`lastCompletedIdsByType\`: object — per-task-type cursor (only \`sunspot\` and \`magnetogram\`)

SolarHub only recognizes two task types at the moment: \`sunspot\` and \`magnetogram\`.
The \`lastCompletedIdsByType\` object stores the last completed ID for each type so
the app can resume on the next image.

## Privacy & Safety

This repo is public so SolarHub can read/write \`progress.json\` using the GitHub
Contents API. The file contains no personally identifying information other
than the fact that the repository belongs to your GitHub account.

---

Generated by SolarHub — you can safely delete or inspect this repo at any time.
`;
  
  // Add stronger guidance, site/repo links and funding info, inserting owner where appropriate
  const enhanced = `# SolarHub Data for ${config.owner}

IMPORTANT: Do NOT delete this repository. SolarHub depends on this public repository to store a single file (\`progress.json\`) that tracks your daily progress and points. Deleting it will remove your stored progress and may break the app's resume behavior.

## Project site

- Website: https://space-gen.github.io/solarhub
- SolarHub repository: https://github.com/space-gen/solarhub

## What this repo contains

- \`progress.json\` — your personal progress document (schemaVersion: 2)

SolarHub uses this public repo only to persist a tiny JSON file that tracks which images you've already annotated today and your points/streak. Nothing else is written here by the app.

## progress.json schema (summary)

- \`schemaVersion\`: number — currently 2
- \`points\`: integer — total points you've earned
- \`streak\`: integer — consecutive-day contribution streak
- \`lastActiveDate\`: string|null — ISO date of last activity
- \`lastCompletedIdsByType\`: object — per-task-type cursor (only \`sunspot\` and \`magnetogram\`)

The \`lastCompletedIdsByType\` object stores the last completed ID for each type so the app can resume on the next image.

## Support / Funding

If you find SolarHub useful, you can support development:

- GitHub Sponsors: https://github.com/sponsors/${config.owner}
- Ko-fi: https://ko-fi.com/${config.owner}
- Patreon: https://www.patreon.com/${config.owner}

## Funding (project maintainer)

[![Sponsor on GitHub](https://img.shields.io/badge/Sponsor-GitHub-ff69b4?style=for-the-badge&logo=github-sponsors)](https://github.com/sponsors/soumyadipkarforma)
[![Patreon](https://img.shields.io/badge/Support-Patreon-FF424D?style=for-the-badge&logo=patreon)](https://www.patreon.com/SoumyadipKarforma)
[![Buy Me a Coffee](https://img.shields.io/badge/Support-Buy%20Me%20a%20Coffee-orange?style=for-the-badge&logo=buy-me-a-coffee)](https://buymeacoffee.com/soumyadipkarforma)

## Meta / Description

Site meta: space-gen.github.io/solarhub — SolarHub is a lightweight citizen-science web app for annotating solar imagery and collecting labels for scientific use.

## Privacy & Safety

This repo is public so SolarHub can read/write \`progress.json\` using the GitHub Contents API. The file contains no personally identifying information beyond the fact that the repository belongs to your GitHub account.

---

Generated by SolarHub — this README was created automatically to explain the repo's purpose and provide links to the site and funding options.
`;

  // Prefer the enhanced README when creating/updating the repo
  const finalContent = enhanced;

  try {
    // Try to fetch existing README
    const getResp = await fetch(`https://api.github.com/repos/${config.owner}/${config.repo}/contents/${readmePath}`, {
      headers: { 'Authorization': `Bearer ${token}` },
    });

    const body: any = {
      message: 'Add SolarHub README',
      content: encodeBase64Text(finalContent ?? content),
    };

    if (getResp.ok) {
      const existing = await getResp.json();
      if (existing && existing.sha) body.sha = existing.sha;
    }

    const putResp = await fetch(`https://api.github.com/repos/${config.owner}/${config.repo}/contents/${readmePath}`, {
      method: 'PUT',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Content-Type': 'application/json',
        'Accept': 'application/vnd.github.v3+json',
      },
      body: JSON.stringify(body),
    });

    if (!putResp.ok) {
      const text = await putResp.text();
      console.warn('[GithubSyncService] Failed to add README:', putResp.status, text);
    }
  } catch (err) {
    console.warn('[GithubSyncService] upsertRepoReadme failed:', err);
  }
}

function normalizeProgress(value: unknown): ProgressDocument {
  if (!value || typeof value !== 'object') return defaultProgress();
  const raw = value as Partial<ProgressDocument> & {
    lastCompletedId?: string | null;
    completedIds?: string[];
    lastCompletedIdsByType?: Partial<Record<TaskType, string | null>>;
  };

  const lastCompletedIdsByType = createEmptyLastCompletedIdsByType();
  for (const taskType of TASK_TYPES) {
    const rawValue = raw.lastCompletedIdsByType?.[taskType];
    if (typeof rawValue === 'string') {
      lastCompletedIdsByType[taskType] = rawValue;
    }
  }

  return {
    schemaVersion: 2,
    points: Number.isFinite(raw.points) ? Math.max(0, Number(raw.points)) : 0,
    streak: Number.isFinite(raw.streak) ? Math.max(0, Number(raw.streak)) : 0,
    lastActiveDate: typeof raw.lastActiveDate === 'string' ? raw.lastActiveDate : null,
    lastCompletedIdsByType,
    updatedAt: typeof raw.updatedAt === 'string' ? raw.updatedAt : new Date().toISOString(),
  };
}

function encodeBase64Json(doc: ProgressDocument): string {
  const json = JSON.stringify(doc, null, 2);
  return btoa(unescape(encodeURIComponent(json)));
}

function decodeBase64Json(content: string): ProgressDocument {
  const json = decodeURIComponent(escape(atob(content.replace(/\n/g, ''))));
  const parsed = JSON.parse(json) as unknown;
  return normalizeProgress(parsed);
}

function queueWrite<T>(operation: () => Promise<T>): Promise<T> {
  const result = writeQueue.then(operation, operation);
  writeQueue = result.then(() => undefined, () => undefined);
  return result;
}

/**
 * Get or create user's public `solarhub-data` repository.
 */
export async function ensureUserRepo(): Promise<RepoConfig> {
  const token = getStoredToken();
  const config = getCurrentRepoConfig();

  if (!token) {
    throw new Error('User not authenticated');
  }

  // Create public repo (idempotent; falls back to GET if already exists)
  const response = await fetch('https://api.github.com/user/repos', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${token}`,
      'Content-Type': 'application/json',
      'Accept': 'application/vnd.github.v3+json',
    },
    body: JSON.stringify({
      name: config.repo,
      private: false,
      description: 'SolarHub per-user progress store (progress.json)',
      auto_init: false,
    }),
  });

  if (!response.ok) {
    // Repo might already exist, try to fetch it
    const getResponse = await fetch(
      `https://api.github.com/repos/${config.owner}/${config.repo}`,
      {
        headers: { 'Authorization': `Bearer ${token}` },
      }
    );

    if (!getResponse.ok) {
      throw new Error(`Failed to create or find repo: ${response.status}`);
    }
  }

  // Ensure a helpful README exists in the repo (create or update)
  try {
    await upsertRepoReadme(config, token);
  } catch (err) {
    // Non-fatal — repo exists even if README update failed
  }

  return config;
}

/**
 * Fetch progress.json from user's repo.
 */
export async function fetchProgressFile(): Promise<{
  progress: ProgressDocument;
  sha: string;
} | null> {
  const token = getStoredToken();
  const config = getCurrentRepoConfig();

  if (!token) {
    throw new Error('Not authenticated');
  }

  try {
    const response = await fetch(
      `https://api.github.com/repos/${config.owner}/${config.repo}/contents/${PROGRESS_FILE_NAME}`,
      {
        headers: { 'Authorization': `Bearer ${token}` },
      }
    );

    if (response.status === 404) {
      return null;
    }

    if (!response.ok) {
      throw new Error(`GitHub API ${response.status}`);
    }

    const data = await response.json() as { content: string; sha: string };
    return { progress: decodeBase64Json(data.content), sha: data.sha };
  } catch (error) {
    console.error('[GithubSyncService] Fetch failed:', error);
    throw error;
  }
}

/**
 * Upload progress.json to user's repo.
 */
export async function uploadProgressFile(
  progress: ProgressDocument,
  sha?: string
): Promise<{ sha: string }> {
  const token = getStoredToken();
  const config = getCurrentRepoConfig();

  if (!token) {
    throw new Error('Not authenticated');
  }

  const base64Content = encodeBase64Json(progress);

  const body: Record<string, string> = {
    message: `Update progress.json - ${new Date().toISOString()}`,
    content: base64Content,
  };

  if (sha) {
    body.sha = sha;
  }

  try {
    const response = await fetch(
      `https://api.github.com/repos/${config.owner}/${config.repo}/contents/${PROGRESS_FILE_NAME}`,
      {
        method: 'PUT',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json',
          'Accept': 'application/vnd.github.v3+json',
        },
        body: JSON.stringify(body),
      }
    );

    console.info('[GithubSyncService] uploadProgressFile response status ->', response.status);

    if (response.status === 409) {
      console.warn('[GithubSyncService] Conflict detected (409), fetching latest SHA...');
      const latest = await fetchProgressFile();
      if (latest) {
        return uploadProgressFile(progress, latest.sha);
      }
      throw new Error('Conflict resolution failed');
    }

    const text = await response.text();
    if (!response.ok) {
      console.error('[GithubSyncService] uploadProgressFile failed body ->', text);
      throw new Error(`GitHub API ${response.status}: ${text}`);
    }

    let data: any = {};
    try { data = JSON.parse(text); } catch { data = { content: { sha: '' } }; }
    console.info('[GithubSyncService] uploadProgressFile success sha ->', data?.content?.sha);
    return { sha: data.content?.sha || '' };
  } catch (error) {
    console.error('[GithubSyncService] Upload failed:', error);
    throw error;
  }
}

/**
 * Initialize by ensuring repo + progress.json exist and then loading cache.
 */
export async function initializeFromGitHub(): Promise<void> {
  const token = getStoredToken();
  if (!token) return;

  await ensureUserRepo();
  const remote = await fetchProgressFile();

  if (remote) {
    // Ensure the fetched document is normalized to only include the
    // supported task types (currently `sunspot` and `magnetogram`).
    const normalized = normalizeProgress(remote.progress);
    cachedProgress = normalized;
    cachedSha = remote.sha;

    // If the remote contained extra/legacy task-type keys, overwrite the
    // remote progress.json with the normalized version so the repo is
    // migrated in-place to the two-type model.
    const remoteTypes = Object.keys((remote.progress as any).lastCompletedIdsByType || {});
    const allowedTypes = new Set(TASK_TYPES);
    const hasExtra = remoteTypes.some(t => !allowedTypes.has(t as TaskType));
    if (hasExtra) {
      try {
        await saveProgressToGitHub(normalized);
        console.info('[GithubSyncService] Migrated progress.json to supported task types');
      } catch (err) {
        console.warn('[GithubSyncService] Failed to migrate progress.json:', err);
      }
    }

    return;
  }

  const initial = defaultProgress();
  const uploaded = await uploadProgressFile(initial);
  cachedProgress = initial;
  cachedSha = uploaded.sha;
}

/**
 * Returns the current progress from cache/remote.
 */
export async function loadProgressFromGitHub(): Promise<ProgressDocument> {
  if (cachedProgress) {
    return {
      ...cachedProgress,
      lastCompletedIdsByType: { ...cachedProgress.lastCompletedIdsByType },
    };
  }

  await initializeFromGitHub();

  if (!cachedProgress) {
    cachedProgress = defaultProgress();
  }

  return {
    ...cachedProgress,
    lastCompletedIdsByType: { ...cachedProgress.lastCompletedIdsByType },
  };
}

/**
 * Save progress.json and refresh local cache.
 */
export async function saveProgressToGitHub(nextProgress: ProgressDocument): Promise<ProgressDocument> {
  return queueWrite(async () => {
    await ensureUserRepo();

    if (!cachedSha) {
      const remote = await fetchProgressFile();
      if (remote) {
        cachedProgress = remote.progress;
        cachedSha = remote.sha;
      }
    }

    const payload: ProgressDocument = {
      ...normalizeProgress(nextProgress),
      updatedAt: new Date().toISOString(),
    };

    const uploaded = await uploadProgressFile(payload, cachedSha);
    cachedProgress = payload;
    cachedSha = uploaded.sha;

    return {
      ...payload,
      lastCompletedIdsByType: { ...payload.lastCompletedIdsByType },
    };
  });
}

/**
 * Backward-compatible helper used by older callers.
 */
export async function syncToGitHub(): Promise<void> {
  const progress = await loadProgressFromGitHub();
  await saveProgressToGitHub(progress);
}
