/**
 * src/vite-env.d.ts
 *
 * Type declarations for Vite's special import features.
 *
 * This file is auto-generated by Vite and should not be edited manually.
 * It augments the TypeScript environment with:
 *  - `import.meta.env.*`  – Vite's environment variable type definitions
 *  - Asset URL imports    – `import url from './image.png'` returns a string
 *  - Raw text imports     – `import text from './file.txt?raw'`
 *  - etc.
 *
 * See: https://vitejs.dev/guide/env-and-mode.html#intellisense-for-typescript
 */

/// <reference types="vite/client" />
